function CML.PriestStartup()

if _Spec == 1 then PQIprefix = "PQI_CodeMyLifeDiscipline_" UnitDispel = {'Disease','Magic'} Coolprefix = "PQI_CodeMyLifeCooldownsDisc_" end
if _Spec == 2 then PQIprefix = "PQI_CodeMyLifeHoly_" UnitDispel = {'Disease','Magic'} Coolprefix = "PQI_CodeMyLifeCooldownsHoly_" end
if _Spec == 3 then PQIprefix = "PQI_CodeMyLifeShadow_" end

_HealingRangeSpell = 139 -- Renew

--[[         ]]		--[[           ]]	--[[           ]]	--[[           ]]
--[[          ]]		  --[[]]		--[[           ]]	--[[           ]]
--[[]]	   --[[]]		  --[[]]		--[[]]	   			--[[]]
--[[]]	   --[[]]		  --[[]]		--[[           ]]	--[[]]
--[[]]	   --[[]]		  --[[]]				   --[[]]	--[[]]	  
--[[          ]]		  --[[]]		--[[           ]]	--[[           ]]
--[[         ]] 	--[[           ]]	--[[           ]]	--[[           ]]

--[[           ]]	--[[         ]]		--[[           ]] 	
--[[           ]]	--[[          ]]	--[[           ]] 	
--[[]]				--[[]]	   --[[]]	--[[]]				
--[[]]				--[[]]	   --[[]]	--[[           ]] 	
--[[]]				--[[]]	   --[[]]		   	   --[[]]	
--[[   		   ]]	--[[          ]]	--[[           ]] 	
--[[   		   ]]	--[[         ]] 	--[[           ]] 	

if _Spec == 1 and CML_Cooldowns_Config == nil then
	Coolprefix = "PQI_CodeMyLifeCooldownsDisc_"
	CML_Cooldowns_Config = {
		name	= "CooldownsDisc",
		author	= "CodeMyLife",
		abilities = {
			{ 	name	= "Racials",
				tooltip	= PlayerHex.."Toggle |cffFFFFFFAutomatic Racials.",
				enable	= true,
				widget = { type = 'select',
					values = {"|cff0DFF00Active","|cffFFE100On CD","|cffD90000Disable"},
					value = 2,
					width = 70,
					tooltip = "|cffFFFFFFChoose desired Cooldowns Options.|cff0DFF00Active will use when you activate Active Cooldowns macro.|cffFFE100On CD will fire on Cooldown regardless of Active Cooldowns.|cffD90000Disable will never use this Cooldown.",	
				},
			},	
			{ 	name	= "Professions CDs",
				tooltip	= PlayerHex.."Toggle |cffFFFFFFAutomatic Professions CDs.",
				enable	= true,
				widget = { type = 'select',
					values = {"|cff0DFF00Active","|cffFFE100On CD","|cffD90000Disable"},
					value = 2,
					width = 70,
					tooltip = "|cffFFFFFFChoose desired Cooldowns Options.|cff0DFF00Active will use when you activate Active Cooldowns macro.|cffFFE100On CD will fire on Cooldown regardless of Active Cooldowns.|cffD90000Disable will never use this Cooldown.",	
				},
			},					
			{ 	name	= "Trinkets",
				tooltip	= PlayerHex.."Toggle |cffFFFFFFAutomatic Trinkets|cff7EBF37.",
				enable	= true,
				widget = { type = 'select',
					values = {"|cff0DFF00Both Active","|cffFFE100Both On CD","|cffD90000Disable"},
					value = 1,
					width = 70,
					tooltip = "|cff7EBF37Choose |cffFFFFFFTrinkets to use|cff7EBF37.",	
				},
			},		
			{ 	name	= "DPS Potion",
				tooltip	= PlayerHex.."Toggle |cffFFFFFFAutomatic Agility Potions|cff7EBF37 when |cffFFFFFFHeroism |cff7EBF37starts.",
				enable	= true,
				widget = { type = 'select',
					values = {PlayerHex.."On Boss","|cffFFFFFFOn Heroism","|cffFFDD00Never"},
					value = 1,
					width = 70,
					tooltip = "|cffFFFFFFSet way to use Potions.",	
				},
			},				
			{ 	name	= "Interrupt",
				tooltip	= PlayerHex.."Toggle |cffFFFFFFAutomatic Interrupt On "..PlayerHex.."Target/Mouseover/Focus.",
				enable	= true,
				widget = { type = 'select',
					values = {PlayerHex.."Random","|cff00CC0030","|cff00CC000"},
					value = 1,
					width = 70,
					tooltip = "|cffFFFFFFSet Treshold to use Interrupt on "..PlayerHex.."Target/Mouseover/Focus.",	
				},
				newSection = true,
			},
		},
	}
	CODEMYLIFE_COOLDOWNS = PQI:AddRotation(CML_Cooldowns_Config)
end

--[[------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------
--------- Priest Discipline -----PQI_CodeMyLifeDiscipline_Name_value-----------------------------------------------------------------------]]

if _Spec == 1 and CML_Disc_config == nil then
	PQIprefix = "PQI_CodeMyLifeDiscipline_"
	_AoEModes = 0
	_RangeSpell = 585
	CML_Disc_config = {
		name	= "Discipline",
		author	= "CodeMyLife",
		abilities = {
			{ 	name	= "Player Status", 
				tooltip	= PlayerHex.."Enables |cffFFFFFFPlayer Bar.",
				enable	= true,
				widget = { type = 'select',
					values 	= {PlayerHex.."Full Bar","|cffFFFFFFMini Bar","|cffD90000Disable"},
					value	= 1,
					width	= 70,
					tooltip	= PlayerHex.."Select what bar style you want.",
				},
			},	   
			{ 	name	= "Player Status X", 
				enable	= true,
				widget	= { type = "numBox",
					min 	= 0,
					max 	= 2000,
					value	= 800,
					width 	= 70,
					step	= 5,
					tooltip	= PlayerHex.."Set Player Status Horizontal Value.",
				},
			},				
			{ 	name	= "Player Status Y", 
				enable	= true,
				widget	= { type = "numBox",
					min 	= 0,
					max 	= 2000,
					value	= 200,
					width 	= 70,
					step	= 5,
					tooltip	= PlayerHex.."Set Player Status Vertical Value.",
				},
			},
			{ 	name	= "Debug",
				tooltip	= PlayerHex.."Displays Rotation locally in chat.",
				enable	= false,
				widget = { type = 'select',
					values 	= {PlayerHex.."Success","|cffD90000Failed","|cffFFFFFFBoth"},
					value	= 1,
					width	= 70,
					tooltip	= PlayerHex.."Select what spells you want to be shown in chat.",
				},
			},	
			{ 	name	= "AoE Helper",
				tooltip	= PlayerHex.."Enables AoE Helper.",
				enable	= false,
				widget = { type = 'select',
					values 	= {PlayerHex.."Forced","|cffD90000Stop"},
					value	= 1,
					width	= 70,
					tooltip	= PlayerHex.."Select how you want the profile to react when you use mouseover ground effects spells.",
				},
			},				
			{ 	name	= "Active Inner Will",
				tooltip	= PlayerHex.."toggle Automatic Inner Will will use Inner Will when out of combat and moving.",
				enable	= true,
				widget	= { type = "numBox",
					value	= 6,
					width 	= 70,
					max 	= 30,
					step	= 1,
					tooltip	= "|cffFFFFFFTime to wait before changing buff.",
				},
			},				
			{ 	name	= "Fortitude",
				enable	= false,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use Fortitude.",
				newSection = true,
			},	
			{ 	name	= "Archangel",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Archangel|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 85,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Archangel|cffFFFFFF.",	
				},
			},
			{ 	name	= "Binding Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Binding Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 70,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Binding Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Cascade",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Cascade|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 70,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Cascade|cffFFFFFF.",	
				},
			},			
			{ 	name	= "Flash Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Flash Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 55,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Flash Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Greater Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Greater Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 65,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Greater Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 75,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Penance",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Penance Healing|cffFFFFFF.",
				widget	= { type = "numBox",
					value	= 45,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Penance Healing|cffFFFFFF.",
				},
			},
			{ 	name	= "Power Word Shield",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Power Word Shield|cffFFFFFF.",
				widget	= { type = "numBox",
					value	= 50,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Power Word Shield|cffFFFFFF.",
				},
			},		
			{ 	name	= "Prayer Of Healing",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Prayer Of Healing|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 70,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Prayer Of Healing|cffFFFFFF.",	
				},
			},						
			{ 	name	= "Prayer Of Mending",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Prayer of Mending|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 85,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Prayer of Mending|cffFFFFFF.",	
				},
			},	
			{ 	name	= "DesperatePrayer",
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				enable	= true,
				widget	= { type = "numBox",
					value	= 25,
					width 	= 70,
					step	= 5,
					tooltip	= "|cffFFFFFFHealth value "..PlayerHex.."to use this Cooldown.",
				},
				newSection = true,
			},	
			{ 	name	= "Fade",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 65,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFFFFFFHealth value "..PlayerHex.."to use this Cooldown.",
				},
			},
			{ 	name	= "Healthstone",
				tooltip	= PlayerHex.."Health value to use |cff33FF33Healthstone.",
				enable	= true,
				widget	= { type = "numBox",
					value	= 25,
					width 	= 70,
					step	= 5,
					tooltip	= "|cffFFFFFFHealth value "..PlayerHex.."to use |cffFFFFFF|cff33FF33Healthstone.",
				},
			},	
			{ 	name	= "ManaFiend",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 85,
					step	= 5,
					width	= 70,
					tooltip	= "|cff0066FFMana |cffFFFFFFto use |cffCC00CCManaFiend|cffFFFFFF.",	
				},
			},
			{ 	name	= "Pain Suppression",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				widget	= { type = "numBox",
					value	= 30,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Pain Suppression |cffFFFFFFon Tank.",
				},
			},
			{ 	name	= "Power Word Speed",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Power Word Speed Boost|cffFFFFFF.",
				widget	= { type = "numBox",
					value	= 30,
					step	= 5,
					width	= 70,
					tooltip	= "|cff0066FFMana |cffFFFFFFto use |cffFFCC33Power Word Speed Boost|cffFFFFFF.",
				},
			},
			{ 	name	= "Void Shift",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffCC00CCVoid Shift|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 22,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffCC00CCVoid Shift|cffFFFFFF.",	
				},
			},	
		},
		--[[ Keybinds ]]
		hotkeys = {
			{	name	= "Pause",
				enable	= true,
				hotkeys	= {'la'},
				tooltip	= PlayerHex.."Assign Pause Will Stop Rotation.",
			},
			{	name	= "Set Focus",
				enable	= true,
				hotkeys	= {'lc'},
				tooltip	= PlayerHex.."Assign Mouseover Focus Set focus to mouseover.",
			},
			{	name	= "Power Word Barrier",
				enable	= true,
				hotkeys	= {'lc'},
				tooltip	= PlayerHex.."Assign Power Word Barrier Keybind.",
			},	
			{	name	= "Mass Dispel",
				enable	= true,
				hotkeys	= {'ls'},
				tooltip	= PlayerHex.."Assign Mass Dispel Keybind.",
			},			
		},
	}
	CODEMYLIFE_DISCIPLINE = PQI:AddRotation(CML_Disc_config)
end



--[[]]	   --[[]]	--[[           ]]	--[[]]				--[[]]	  --[[]]
--[[]]	   --[[]]	--[[           ]]	--[[]]				--[[]]	  --[[]]
--[[           ]]	--[[]]	   --[[]]	--[[]]				   --[[    ]]	   
--[[           ]]	--[[]]	   --[[]]	--[[]]				   --[[    ]]
--[[           ]]	--[[]]	   --[[]]	--[[]]					 --[[]]
--[[]]	   --[[]]	--[[           ]]	--[[           ]]		 --[[]]
--[[]]	   --[[]]	--[[           ]]	--[[           ]]		 --[[]]

--[[           ]]	--[[         ]]		--[[           ]] 	
--[[           ]]	--[[          ]]	--[[           ]] 	
--[[]]				--[[]]	   --[[]]	--[[]]				
--[[]]				--[[]]	   --[[]]	--[[           ]] 	
--[[]]				--[[]]	   --[[]]		   	   --[[]]	
--[[   		   ]]	--[[          ]]	--[[           ]] 	
--[[   		   ]]	--[[         ]] 	--[[           ]] 	

if _Spec == 2 and CML_Cooldowns_Config == nil then
	Coolprefix = "PQI_CodeMyLifeCooldownsHoly_"
	CML_Cooldowns_Config = {
		name	= "CooldownsHoly",
		author	= "CodeMyLife",
		abilities = {
			{ 	name	= "Racials",
				tooltip	= PlayerHex.."Toggle |cffFFFFFFAutomatic Racials.",
				enable	= true,
				widget = { type = 'select',
					values = {"|cff0DFF00Active","|cffFFE100On CD","|cffD90000Disable"},
					value = 2,
					width = 70,
					tooltip = "|cffFFFFFFChoose desired Cooldowns Options.|cff0DFF00Active will use when you activate Active Cooldowns macro.|cffFFE100On CD will fire on Cooldown regardless of Active Cooldowns.|cffD90000Disable will never use this Cooldown.",	
				},
			},	
			{ 	name	= "Professions CDs",
				tooltip	= PlayerHex.."Toggle |cffFFFFFFAutomatic Professions CDs.",
				enable	= true,
				widget = { type = 'select',
					values = {"|cff0DFF00Active","|cffFFE100On CD","|cffD90000Disable"},
					value = 2,
					width = 70,
					tooltip = "|cffFFFFFFChoose desired Cooldowns Options.|cff0DFF00Active will use when you activate Active Cooldowns macro.|cffFFE100On CD will fire on Cooldown regardless of Active Cooldowns.|cffD90000Disable will never use this Cooldown.",	
				},
			},					
			{ 	name	= "Trinkets",
				tooltip	= PlayerHex.."Toggle |cffFFFFFFAutomatic Trinkets|cff7EBF37.",
				enable	= true,
				widget = { type = 'select',
					values = {"|cff0DFF00Both Active","|cffFFE100Both On CD","|cffD90000Disable"},
					value = 1,
					width = 70,
					tooltip = "|cff7EBF37Choose |cffFFFFFFTrinkets to use|cff7EBF37.",	
				},
			},		
			{ 	name	= "DPS Potion",
				tooltip	= PlayerHex.."Toggle |cffFFFFFFAutomatic Agility Potions|cff7EBF37 when |cffFFFFFFHeroism |cff7EBF37starts.",
				enable	= true,
				widget = { type = 'select',
					values = {PlayerHex.."On Boss","|cffFFFFFFOn Heroism","|cffFFDD00Never"},
					value = 1,
					width = 70,
					tooltip = "|cffFFFFFFSet way to use Potions.",	
				},
			},				
			{ 	name	= "Interrupt",
				tooltip	= PlayerHex.."Toggle |cffFFFFFFAutomatic Interrupt On "..PlayerHex.."Target/Mouseover/Focus.",
				enable	= true,
				widget = { type = 'select',
					values = {PlayerHex.."Random","|cff00CC0030","|cff00CC000"},
					value = 1,
					width = 70,
					tooltip = "|cffFFFFFFSet Treshold to use Interrupt on "..PlayerHex.."Target/Mouseover/Focus.",	
				},
				newSection = true,
			},
		},
	}
	CODEMYLIFE_COOLDOWNS = PQI:AddRotation(CML_Cooldowns_Config)
end

--[[------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------
--------- Priest Holy -----PQI_CodeMyLifeHoly_Name_value-----------------------------------------------------------------------]]

if _Spec == 2 and CML_Holy_config == nil then
	PQIprefix = "PQI_CodeMyLifeHoly_"
	_AoEModes = 0
	_RangeSpell = 585
	CML_Holy_config = {
		name	= "Holy",
		author	= "CodeMyLife",
		abilities = {
			{ 	name	= "Player Status", 
				tooltip	= PlayerHex.."Enables |cffFFFFFFPlayer Bar.",
				enable	= true,
				widget = { type = 'select',
					values 	= {PlayerHex.."Full Bar","|cffFFFFFFMini Bar","|cffD90000Disable"},
					value	= 1,
					width	= 70,
					tooltip	= PlayerHex.."Select what bar style you want.",
				},
			},	   
			{ 	name	= "Player Status X", 
				enable	= true,
				widget	= { type = "numBox",
					min 	= 0,
					max 	= 2000,
					value	= 800,
					width 	= 70,
					step	= 5,
					tooltip	= PlayerHex.."Set Player Status Horizontal Value.",
				},
			},				
			{ 	name	= "Player Status Y", 
				enable	= true,
				widget	= { type = "numBox",
					min 	= 0,
					max 	= 2000,
					value	= 200,
					width 	= 70,
					step	= 5,
					tooltip	= PlayerHex.."Set Player Status Vertical Value.",
				},
			},
			{ 	name	= "Debug",
				tooltip	= PlayerHex.."Displays Rotation locally in chat.",
				enable	= false,
				widget = { type = 'select',
					values 	= {PlayerHex.."Success","|cffD90000Failed","|cffFFFFFFBoth"},
					value	= 1,
					width	= 70,
					tooltip	= PlayerHex.."Select what spells you want to be shown in chat.",
				},
			},		
			{ 	name	= "AoE Helper",
				tooltip	= PlayerHex.."Enables AoE Helper.",
				enable	= false,
				widget = { type = 'select',
					values 	= {PlayerHex.."Forced","|cffD90000Stop"},
					value	= 1,
					width	= 70,
					tooltip	= PlayerHex.."Select how you want the profile to react when you use mouseover ground effects spells.",
				},
			},	
			{ 	name	= "Active Inner Will",
				tooltip	= PlayerHex.."toggle Automatic Inner Will will use Inner Will when out of combat and moving.",
				enable	= true,
				widget	= { type = "numBox",
					value	= 6,
					width 	= 70,
					max 	= 30,
					step	= 1,
					tooltip	= "|cffFFFFFFTime to wait before changing buff.",
				},
				newSection = true,
			},				
			{ 	name	= "Fortitude",
				enable	= false,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use Fortitude.",
				newSection = true,
			},				
			{ 	name	= "Renew",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Renew|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 85,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Renew|cffFFFFFF.",	
				},
			},
			{ 	name	= "Binding Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Binding Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 70,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Binding Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Flash Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Flash Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 55,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Flash Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Greater Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Greater Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 65,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Greater Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Guardian Spirit",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Guardian Spirit|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 75,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Guardian Spirit|cffFFFFFF.",	
				},
			},
			{ 	name	= "Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 75,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Power Word Shield",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Power Word Shield|cffFFFFFF.",
				widget	= { type = "numBox",
					value	= 50,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Power Word Shield|cffFFFFFF.",
				},
			},		
			{ 	name	= "Prayer Of Healing",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Prayer Of Healing|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 70,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Prayer Of Healing|cffFFFFFF.",	
				},
			},		
			{ 	name	= "Prayer Of Mending",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Prayer of Mending|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 85,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Prayer of Mending|cffFFFFFF.",	
				},
			},	
			{ 	name	= "Cascade",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				widget	= { type = "numBox",
					value	= 30,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Cascade .",
				},
			},
			{ 	name	= "Desperate Prayer",
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				enable	= true,
				widget	= { type = "numBox",
					value	= 25,
					width 	= 70,
					step	= 5,
					tooltip	= "|cffFFFFFFHealth value "..PlayerHex.."to use this Cooldown.",
				},
				newSection = true,
			},	
			{ 	name	= "Fade",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 65,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFFFFFFHealth value "..PlayerHex.."to use this Cooldown.",
				},
			},
			{ 	name	= "Healthstone",
				tooltip	= PlayerHex.."Health value to use |cff33FF33Healthstone.",
				enable	= true,
				widget	= { type = "numBox",
					value	= 25,
					width 	= 70,
					step	= 5,
					tooltip	= "|cffFFFFFFHealth value "..PlayerHex.."to use |cffFFFFFF|cff33FF33Healthstone.",
				},
			},	
			{ 	name	= "ManaFiend",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 85,
					step	= 5,
					width	= 70,
					tooltip	= "|cff0066FFMana |cffFFFFFFto use |cffCC00CCManaFiend|cffFFFFFF.",	
				},
			},
			{ 	name	= "Power Word Speed",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Power Word Speed Boost|cffFFFFFF.",
				widget	= { type = "numBox",
					value	= 30,
					step	= 5,
					width	= 70,
					tooltip	= "|cff0066FFMana |cffFFFFFFto use |cffFFCC33Power Word Speed Boost|cffFFFFFF.",
				},
			},
			{ 	name	= "Serenity",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				widget	= { type = "numBox",
					value	= 30,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Serenity |cffFFFFFFon Tank.",
				},
			},
			{ 	name	= "Void Shift",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffCC00CCVoid Shift|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 22,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffCC00CCVoid Shift|cffFFFFFF.",	
				},
			},		
		},
		--[[ Keybinds ]]
		hotkeys = {
			{	name	= "Pause",
				enable	= true,
				hotkeys	= {'la'},
				tooltip	= PlayerHex.."Assign Pause Will Stop Rotation.",
			},
			{	name	= "Set Focus",
				enable	= true,
				hotkeys	= {'lc'},
				tooltip	= PlayerHex.."Assign Mouseover Focus Set focus to mouseover.",
			},
			{	name	= "Power Word Barrier",
				enable	= true,
				hotkeys	= {'lc'},
				tooltip	= PlayerHex.."Assign Power Word Barrier Keybind.",
			},	
			{	name	= "Mass Dispel",
				enable	= true,
				hotkeys	= {'ls'},
				tooltip	= PlayerHex.."Assign Mass Dispel Keybind.",
			},			
		},
	}
	CODEMYLIFE_HOLY = PQI:AddRotation(CML_Holy_config)
end	


--[[           ]]	--[[]]	   --[[]]		  --[[]]		--[[         ]]		--[[           ]]	--[[]] 	   --[[]]
--[[           ]]	--[[]]	   --[[]]	     --[[  ]]		--[[          ]]	--[[           ]]	--[[]] 	   --[[]]
--[[]]				--[[]]	   --[[]]	    --[[    ]] 		--[[]]	   --[[]]	--[[]]	   --[[]]	--[[ ]]   --[[ ]]
--[[           ]]	--[[           ]]	   --[[      ]] 	--[[]]	   --[[]]	--[[]]	   --[[]]	--[[           ]]
		   --[[]] 	--[[]]	   --[[]] 	  --[[        ]]	--[[]]	   --[[]]	--[[]]	   --[[]]	--[[           ]]
--[[           ]]	--[[]]	   --[[]]	 --[[]]    --[[]]	--[[          ]]	--[[           ]]	--[[ ]]   --[[ ]]
--[[           ]]	--[[]]	   --[[]]	--[[]]      --[[]]	--[[         ]]		--[[           ]]	 --[[]]   --[[]]

--[[------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------
--------- Priest Shadow -----PQI_CodeMyLifeShadow_Name_value-----------------------------------------------------------------------]]

if _Spec == 3 and CML_Shadow_config == nil then
	PQIprefix = "PQI_CodeMyLifeShadow_"
	_AoEModes = 0
	_RangeSpell = 585
	CML_Disc_config = {
		name	= "Shadow",
		author	= "CodeMyLife",
		abilities = {
			{ 	name	= "Player Status", 
				tooltip	= PlayerHex.."Enables |cffFFFFFFPlayer Bar.",
				enable	= true,
				widget = { type = 'select',
					values 	= {PlayerHex.."Full Bar","|cffFFFFFFMini Bar","|cffD90000Disable"},
					value	= 1,
					width	= 70,
					tooltip	= PlayerHex.."Select what bar style you want.",
				},
			},	   
			{ 	name	= "Player Status X", 
				enable	= true,
				widget	= { type = "numBox",
					min 	= 0,
					max 	= 2000,
					value	= 800,
					width 	= 70,
					step	= 5,
					tooltip	= PlayerHex.."Set Player Status Horizontal Value.",
				},
			},				
			{ 	name	= "Player Status Y", 
				enable	= true,
				widget	= { type = "numBox",
					min 	= 0,
					max 	= 2000,
					value	= 200,
					width 	= 70,
					step	= 5,
					tooltip	= PlayerHex.."Set Player Status Vertical Value.",
				},
			},
			{ 	name	= "Debug",
				tooltip	= PlayerHex.."Displays Rotation locally in chat.",
				enable	= false,
				widget = { type = 'select',
					values 	= {PlayerHex.."Success","|cffD90000Failed","|cffFFFFFFBoth"},
					value	= 1,
					width	= 70,
					tooltip	= PlayerHex.."Select what spells you want to be shown in chat.",
				},
			},		
			{ 	name	= "AoE Helper",
				tooltip	= PlayerHex.."Enables AoE Helper.",
				enable	= false,
				widget = { type = 'select',
					values 	= {PlayerHex.."Forced","|cffD90000Stop"},
					value	= 1,
					width	= 70,
					tooltip	= PlayerHex.."Select how you want the profile to react when you use mouseover ground effects spells.",
				},
			},	
			{ 	name	= "Combat Check", 
				tooltip	= PlayerHex.."Check to activate Combat Check.",
				enable	= true,
			},
			{ 	name	= "Active Inner Will",
				tooltip	= PlayerHex.."toggle Automatic Inner Will will use Inner Will when out of combat and moving.",
				enable	= true,
				widget	= { type = "numBox",
					value	= 6,
					width 	= 70,
					max 	= 30,
					step	= 1,
					tooltip	= "|cffFFFFFFTime to wait before changing buff.",
				},
			},				
			{ 	name	= "Fortitude",
				enable	= false,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use Fortitude.",
				newSection = true,
			},	
			{ 	name	= "Archangel",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Archangel|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 85,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Archangel|cffFFFFFF.",	
				},
			},
			{ 	name	= "Binding Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Binding Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 70,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Binding Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Flash Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Flash Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 55,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Flash Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Greater Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Greater Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 65,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Greater Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Heal",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Heal|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 75,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Heal|cffFFFFFF.",	
				},
			},
			{ 	name	= "Penance",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Penance Healing|cffFFFFFF.",
				widget	= { type = "numBox",
					value	= 45,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Penance Healing|cffFFFFFF.",
				},
			},
			{ 	name	= "Power Word Shield",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Power Word Shield|cffFFFFFF.",
				widget	= { type = "numBox",
					value	= 50,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Power Word Shield|cffFFFFFF.",
				},
			},		
			{ 	name	= "Prayer Of Mending",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Prayer of Mending|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 85,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Prayer of Mending|cffFFFFFF.",	
				},
			},	
			{ 	name	= "DesperatePrayer",
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				enable	= true,
				widget	= { type = "numBox",
					value	= 25,
					width 	= 70,
					step	= 5,
					tooltip	= "|cffFFFFFFHealth value "..PlayerHex.."to use this Cooldown.",
				},
				newSection = true,
			},	
			{ 	name	= "Fade",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 65,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFFFFFFHealth value "..PlayerHex.."to use this Cooldown.",
				},
			},
			{ 	name	= "Healthstone",
				tooltip	= PlayerHex.."Health value to use |cff33FF33Healthstone.",
				enable	= true,
				widget	= { type = "numBox",
					value	= 25,
					width 	= 70,
					step	= 5,
					tooltip	= "|cffFFFFFFHealth value "..PlayerHex.."to use |cffFFFFFF|cff33FF33Healthstone.",
				},
			},	
			{ 	name	= "ManaFiend",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 85,
					step	= 5,
					width	= 70,
					tooltip	= "|cff0066FFMana |cffFFFFFFto use |cffCC00CCManaFiend|cffFFFFFF.",	
				},
			},
			{ 	name	= "Pain Suppression",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck "..PlayerHex.."to use this Cooldown.",
				widget	= { type = "numBox",
					value	= 30,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffFFCC33Pain Suppression |cffFFFFFFon Tank.",
				},
			},
			{ 	name	= "Power Word Speed",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffFFCC33Power Word Speed Boost|cffFFFFFF.",
				widget	= { type = "numBox",
					value	= 30,
					step	= 5,
					width	= 70,
					tooltip	= "|cff0066FFMana |cffFFFFFFto use |cffFFCC33Power Word Speed Boost|cffFFFFFF.",
				},
			},
			{ 	name	= "Void Shift",
				enable	= true,
				tooltip	= "|cffFFFFFFCheck to activate |cffCC00CCVoid Shift|cffFFFFFF.",
				widget	= { type = "numBox",
					min		= 1,
					max		= 100,
					value	= 22,
					step	= 5,
					width	= 70,
					tooltip	= "|cffFF0000Health |cffFFFFFFto use |cffCC00CCVoid Shift|cffFFFFFF.",	
				},
			},
			{ 	name	= "Racials",
				tooltip	= PlayerHex.."toggle Automatic Racials.",
				enable	= true,
				widget = { type = 'select',
					values = {"|cff0DFF00Active","|cffFFE100On CD","|cffD90000Disable"},
					value = 2,
					width = 70,
					tooltip = "|cffFFFFFFChoose desired Cooldowns Options.|cff0DFF00Active will use when you activate Active Cooldowns macro.|cffFFE100On CD will fire on Cooldown regardless of Active Cooldowns.|cffD90000Disable will never use this Cooldown.",	
				},
				newSection = true,
			},	
			{ 	name	= "Professions CDs",
				tooltip	= PlayerHex.."toggle Automatic Professions CDs.",
				enable	= true,
				widget = { type = 'select',
					values = {"|cff0DFF00Active","|cffFFE100On CD","|cffD90000Disable"},
					value = 2,
					width = 70,
					tooltip = "|cffFFFFFFChoose desired Cooldowns Options.|cff0DFF00Active will use when you activate Active Cooldowns macro.|cffFFE100On CD will fire on Cooldown regardless of Active Cooldowns.|cffD90000Disable will never use this Cooldown.",	
				},
			},					
			{ 	name	= "Trinkets",
				tooltip	= PlayerHex.."toggle Automatic Trinkets.",
				enable	= true,
				widget = { type = 'select',
					values = {"|cff0DFF00Both Active","|cffFFE100Both On CD","|cffD90000Disable"},
					value = 2,
					width = 70,
					tooltip = PlayerHex.."Choose Trinkets to use.",	
				},
			},		
			{ 	name	= "DPS Potion on Heroism",
				tooltip	= PlayerHex.."toggle Automatic DPS Potions when Heroism starts.",
				enable	= true,
			},			
		},
		--[[ Keybinds ]]
		hotkeys = {
			{	name	= "Pause",
				enable	= true,
				hotkeys	= {'la'},
				tooltip	= PlayerHex.."Assign Pause Will Stop Rotation.",
			},
			{	name	= "Set Focus",
				enable	= true,
				hotkeys	= {'lc'},
				tooltip	= PlayerHex.."Assign Mouseover Focus Set focus to mouseover.",
			},
			{	name	= "Power Word Barrier",
				enable	= true,
				hotkeys	= {'lc'},
				tooltip	= PlayerHex.."Assign Power Word Barrier Keybind.",
			},	
			{	name	= "Mass Dispel",
				enable	= true,
				hotkeys	= {'ls'},
				tooltip	= PlayerHex.."Assign Mass Dispel Keybind.",
			},			
		},
	}
	CODEMYLIFE_SHADOW = PQI:AddRotation(CML_Shadow_config)
end	

--[[           ]]	--[[]]	   --[[]]	--[[]]	   --[[]]	--[[   		   ]]	--[[   		   ]]	--[[   		   ]]	--[[           ]]	--[[]]	   --[[]]
--[[           ]]	--[[]]	   --[[]]	--[[  ]]   --[[]]	--[[   		   ]]	--[[   		   ]]	--[[   		   ]]	--[[           ]]	--[[  ]]   --[[]]
--[[]]				--[[]]	   --[[]]	--[[    ]] --[[]]   --[[]]					 --[[ ]]			 --[[ ]]		--[[]]	   --[[]]	--[[    ]] --[[]]
--[[           ]]	--[[]]	   --[[]]	--[[           ]]	--[[]]					 --[[ ]]			 --[[ ]]		--[[]]	   --[[]]	--[[           ]]
--[[           ]]	--[[]]	   --[[]]	--[[   		   ]]	--[[]]					 --[[ ]]			 --[[ ]]		--[[]]	   --[[]]	--[[   		   ]]
--[[]]	   			--[[           ]]	--[[]]	 --[[  ]]	--[[   		   ]]		 --[[ ]]		--[[   		   ]]	--[[           ]]	--[[]]	 --[[  ]]
--[[]]	   			--[[           ]]	--[[]]	   --[[]]	--[[   		   ]]		 --[[ ]]		--[[   		   ]]	--[[           ]]	--[[]]	   --[[]]
if not PriestFunctions then
	PriestFunctions = true

	macros = { 
	    ["ActiveCooldowns"]   		= false, 
	    ["ActiveDPS"]   			= false, 
	    ["ActiveDispel"]   			= true, 
	    ["ActiveHealing"]   		= true, 
	    ["AoE"]    					= 1,  
	    ["Pause"]					= false,
	} 	

	_Queues = {	
		[3]							= false,
		[126135]					= false, -- Lightwell
		[88685]						= false, -- Holy Word Sanctuary
		[108921]					= false, -- Psyfiend
		[64843]						= false, -- Divine Hymn
		[64901]						= false, -- Hymn of Hope
		[8122]						= false, -- Psychic Scream
		[48045]						= false, -- Mind Sear
		[73325]						= false, -- Leap of Faith
		[9484]						= false, -- Shackle Undead
		[32375]						= false, -- Mass Dispel
		[6346]						= false, -- Fear Ward
	}

	function CML.Evangelism()
		Stacks = select(4,UnitBuffID("player",81661))
		if Stacks == 5 then
			return true
		end
	end

	function CML.BindingHeal()
		if "player" == nNova[1].unit or not PQIprefix then return false
		elseif _G[PQIprefix.."BindingHeal_enable"] and nNova[1].hp <= _G[PQIprefix.."BindingHeal_value"] and CML.GetHP("player") <= _G[PQIprefix.."BindingHeal_value"] then
			ProbablyEngine.dsl.parsedTarget = nNova[1].unit
			return true
		end
	end

	function CML.BubbleMachine()
		-- Hand of Purity return true, SpellTarget, SpellName, EndTime, SpellType
		local BubbleDebuffs = {		
			{ID = 145263, 	Remain = 30, 	Health = 80 }, -- Proving Grounds Healer Debuff.
			{ID = 144331, 	Remain = 10, 	Health = 100 }, -- Iron Prison - Dark Shamans 	
			{ID = 144089, 	Remain = 5, 	Health = 40 }, -- Toxic Mist - Dark Shamans 
			{ID = 143638, 	Remain = 30, 	Health = 30 }, -- Bonecracker 	
		}
		for t=1,#nNova do
			if nNova[t].range == 1 then
				for i=1,#BubbleDebuffs do
					if not UnitDebuffID(nNova[t].unit, 6788) and UnitDebuffID(nNova[t].unit,BubbleDebuffs[i].ID) then
						local SpellName, _, _, _, SpellType, _, EndTime, SpellTarget = UnitDebuffID(nNova[t].unit,BubbleDebuffs[i].ID)
						if EndTime - GetTime() <= BubbleDebuffs[i].Remain and CML.GetHP(nNova[t].unit) <= BubbleDebuffs[i].Health then
							ProbablyEngine.dsl.parsedTarget = nNova[t].unit
							return true
						end
					end
				end
			end
		end
		return false
	end

	function CML.Purify()
		if macros and macros["ActiveDispel"] then
			if UnitExists("boss1") then
				if CML.GetUnitID("boss1") == 71734 then
					if not UnitBuffID("player",144359) then 
						return false
					end
				end
			end
			for i=1, #nNova do
				if nNova[i].dispel == true then 
					ProbablyEngine.dsl.parsedTarget = nNova[i].unit
					return true
				end
			end
		end
		return false
	end


	function CML.Will(value)
		local _ActiveWill = _G[PQIprefix.."ActiveInnerWill_enable"]
		local _ActiveWillValue = _G[PQIprefix.."ActiveInnerWill_value"]
		if GetUnitSpeed("player") > 0 then
			if IsRunning == nil then
				IsRunning = GetTime()
				IsStanding = nil
			end
		else
			if IsStanding == nil then
				IsStanding = GetTime()
				IsRunning = nil
			end
		end
		if IsRunning ~= nil and _ActiveWill and value == 2 then
			if _ActiveWillValue < GetTime() - IsRunning then
				IsRunning = nil
				return true
			end
		end
		if IsStanding ~= nil and _ActiveWill and value == 1 then
			if _ActiveWillValue < GetTime() - IsStanding then
				IsStanding = nil
				return true
			end
		end
	end	

end

end